name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and export
      uses: docker/build-push-action@v4
      with:
        context: .
        tags: krisboorger/crt-model
        outputs: type=docker,dest=/tmp/crt-model.tar
    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: crt-model_image
        path: /tmp/crt-model.tar
      
  push:
    needs: build
  
    runs-on: ubuntu-latest
    
    steps:
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: crt-model_image
        path: /tmp
    - name: Load image
      run: docker load --input /tmp/crt-model_image.tar
    - name: Push the Docker image to registry
      run: docker push krisboorger/crt-model
